### ISSUE TITLE
Breaks wl-copy/wl-paste

### ISSUE THREAD

**Issue by bdaase** [LeonMatthes/mousefollowsfocus#2]
wl-clipoard uses an ugly hack (it maps a transparent toplevel window to steal the focus and fetch the clipboard). When having this extension activated, wl-copy and wl-paste don't work anymore at all and the GNOME session also breaks (the overview randomly opens up after the usage of wl-copy/wl-paste, together with a ton of allocation errors logged).

**Comment by LeonMatthes** [comment]
Took me a while to get around to fix this, but v5 fixes this and is up for review on extensions.gnome.org
