### ISSUE TITLE
Any plans to support GNOME 42?

### ISSUE THREAD

**Issue by ayoisaiah** [LeonMatthes/mousefollowsfocus#3]
![image](https://user-images.githubusercontent.com/13372163/162740083-0ac5da54-15f9-46df-8187-1b6b3fb991e0.png)

**Comment by LeonMatthes** [comment]
Yes, basically once GNOME 42 lands on my laptop (probably with next version of Fedora).

**Comment by LeonMatthes** [comment]
Took me a while longer than expected to get around to updating this but v5 is now up for review on extensions.gnome.org
