### ISSUE TITLE
Support Gnome 45

### ISSUE THREAD

**Issue by MostFrabjous** [LeonMatthes/mousefollowsfocus#9]
Could be more effort than other GNOME releases, see https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45

**Comment by DrOptix** [comment]
I gave it a shot as this is one of my most needed extensions, but I'm not accustomed working with JavaScript in general.
I'll give tomorrow another crack maybe with fresh brain cells I can port it to Gnome 45.

I got it! Not sure if it is the cleanest port, but now on local the extension is again usable on Fedora 39.

**Comment by rustyCircleJones** [comment]
I can confirm that DrOptix's fork is working for me. 

This worked:
```
git clone https://github.com/DrOptix/mousefollowsfocus.git mousefollowsfocus
cd mousefollowsfocus
git checkout issue-9
cd ..
zip -r mousefollowsfocus.zip mousefollowsfocus
gnome-extensions install mousefollowsfocus.zip
```

YMMV

**Comment by MostFrabjous** [comment]
#10 fixes this issue.

**Comment by LeonMatthes** [comment]
I've uploaded the new version to Gnome extensions. Review there may still take a few hours/days, then the new version should be available.

Thanks to @DrOptix for the update :partying_face:
